### PR TITLE
Fix #284

### LINKED ISSUE #284: Install error with R_HOME="*"
```
julia> ENV["R_HOME"]
"*"

julia> using Pkg

julia> Pkg.build("RCall")
  Building CodecZlib → `~/julia_depot_cossio/packages/CodecZlib/DAjXH/deps/build.log`
  Building Conda ────→ `~/julia_depot_cossio/packages/Conda/uQitS/deps/build.log`
  Building RCall ────→ `~/julia_depot_cossio/packages/RCall/RPlFw/deps/build.log`
┌ Error: Error building `RCall`: 
│ ERROR: LoadError: R_HOME is not a directory.
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] top-level scope at logging.jl:311
│  [3] top-level scope at /home/cossio/julia_depot_cossio/packages/RCall/RPlFw/deps/build.jl:19
│  [4] include at ./boot.jl:317 [inlined]
│  [5] include_relative(::Module, ::String) at ./loading.jl:1044
│  [6] include(::Module, ::String) at ./sysimg.jl:29
│  [7] include(::String) at ./client.jl:392
│  [8] top-level scope at none:0
│ in expression starting at /home/cossio/julia_depot_cossio/packages/RCall/RPlFw/deps/build.jl:10
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1097
```

_Originally posted by @cossio in https://github.com/JuliaInterop/RCall.jl/issues/269#issuecomment-446284662_

### PR DESCRIPTION
**Pull request by cossio**
Fix #284

### CODE REVIEW

**Comment by cossio** [comment]
I just tested installing and building RCall with this branch and `R_HOME="*"` and it worked.

**Comment by simonbyrne** [comment]
Maybe the check for `Rhome == "*"` should be first?

**Comment by cossio** [comment]
Would it make a difference?

Like this:

```
if Rhome == "*"
            Rhome = ""
        else
            if isempty(Rhome)
                try Rhome = readchomp(`R RHOME`); catch; end
            end
            @static if Sys.iswindows()
                if isempty(Rhome)
                    try Rhome = WinReg.querykey(WinReg.HKEY_LOCAL_MACHINE,
                                                "Software\\R-Core\\R", "InstallPath"); catch; end
                end
            else
                if !isdir(Rhome)
                    error("R_HOME is not a directory.")
                end
            end
        end
```
?

**Comment by simonbyrne** [comment]
Sort of, but instead of setting `Rhome = ""`, actually do the Conda install part there?

**Comment by cossio** [comment]
@simonbyrne  I see. I did some changes.

**Comment by cossio** [comment]
@simonbyrne Tested installing this again with `R_HOME="*"` and it's working.
I'm not sure if there is a way to set up a CI test for this though.

**Comment by simonbyrne** [comment]
Thanks @cossio for doing this!

**Comment by cossio** [comment]
@randy3k Would it be too complicated to tag a release with this?

**Pull request merged**
