### PR TITLE
Use new Appveyor.jl script

### PR DESCRIPTION
**Pull request by simonbyrne**
This is an easily updatable script

### CODE REVIEW

**Comment by randy3k** [comment]
How about?
```
matrix:
  allow_failures:
	- julia_version: 1
	- julia_version: nightly
```

**Comment by simonbyrne** [comment]
Good point.

Actually, what are the 1.0 blockers? (sorry I haven't looked at this package for a long time)

**Comment by randy3k** [comment]
`AxisArrays.jl`, see https://github.com/JuliaLang/METADATA.jl/pull/16594#issuecomment-412503646 for details

**Comment by randy3k** [comment]
Given the latest update rate of AxisArrays.jl, it may still take some time for them to publish a 1.0 compatible release. What's your opinion of dropping the support of AxisArrarys (temporarily) and tag a release?

**Comment by simonbyrne** [comment]
I think that seems like the best idea.

I think such "optional" dependencies should be handled with [Requires.jl](https://github.com/MikeInnes/Requires.jl)

**Pull request merged**
