### PR TITLE
Implement of the RClass idea

### LINKED ISSUE #138: support for passing custom types?
Hi,
RCall offers a great many standard conversions - julia arrays to R arrays, R lists to julia Dicts etc. But there are also numerous more complex types defined within R and julia packages. Could RCall support an API for implicitly converting between R and julia objects by allowing users to specify a conversion function?

An example: both languages have (several) representations for defining phylogenies: BioJulia has e.g. the Phylo submodule, and the ape R package has the phylo type. It is possible to use RCall code to split the julia Phylogeny type into components (arrays and such), pass them to R, then construct an ape phylo object. It is thus easy to define a conversion function.

The ideal method would be to be able to define such a method using an RCall standard API, putting them either in the relevant julia package, in RCall or an RCall_typeextensions package, and then after defining this method being able to use the conversion implicitly, e.g. 

```
R"plot($phy)"
```

### PR DESCRIPTION
**Pull request by randy3k**
close #138 

An example of usage can be found in [datatime.jl][1].

@richardreeve, I guess you may be interested in it.

[1]: https://github.com/JuliaInterop/RCall.jl/blob/948e1fd1d95304a78ad01150ce08389b56ed6da0/src/convert/datetime.jl

### CODE REVIEW

**Comment by richardreeve** [comment]
Great, I have a brutalist version of my code (richardreeve/Phylo.jl#3) that uses this and it seems to work using `@rget`, though I'm having to create `RObject`s again in a definitely-wrong sort of way. Are there plans for exporting `RClass` and `rcall_p`, which I currently seem to need, or should I just use call `using` on them specifically?

**Comment by randy3k** [comment]
`RClass` and `rcall_p` are not meant to be used by normal users. I guess we should keep them unexported.

**Comment by richardreeve** [comment]
Would it be crazy to create a submodule like `RCall.Extend` for things like `protect`, `unprotect`, `rcall_p`, `RClass`, `isObject`, `isS4` to make it easy to extend the conversion functionality without having loads of `using` statements?

**Comment by randy3k** [comment]
There are too many functions falling into this category. I am not sure if it becomes necessary if most of the internal functions are put in say, `RCall.API`

**Comment by richardreeve** [comment]
Yes, I assumed there would be lots of them tbh, which was why I thought something like `RCall.API` would be useful. Obviously there's also a second much smaller group of functions that need `import`ing too - `rcopy`, `rcopytype`, `sexp`...

**Comment by richardreeve** [comment]
So, I'm completely happy with this, and I don't want to open a can of worms, but when multiple people start providing converters for the same R type, is there going to be a way forward? As things stand (if I understand Julia multiple dispatch correctly, which I probably don't!) are they going to overwrite one another, with the last man standing? That may be fine of course, but I thought I ought to raise it...

**Comment by randy3k** [comment]
I believe only the last overload counts (untested). I guess there is no easy fix for this. Since there should be one and only one output, it should not be very bad to use the last known type.

**Comment by richardreeve** [comment]
Yes, that's what I thought. I guess it's okay - it would be a strange situation using two different Julia types in a single piece of code that match the same R type (and wanting to do conversions!).

**Pull request merged**
