### PR TITLE
Bump version to 0.13.11

### PR DESCRIPTION
**Pull request by nalimilan**
Only changes are dependency versions for Missings and DataFrames.

Cc: @bkamins

### CODE REVIEW

**Review by bkamins — APPROVED** [review]

**Comment by bkamins** [comment]
can you merge, or you need an approval from a member :)?

**Comment by nalimilan** [comment]
Given the limited changes I think I can merge once CI passes.

**Comment by nalimilan** [comment]
https://github.com/JuliaRegistries/General/pull/34998

**Comment by bkamins** [comment]
Thank you!

**Pull request merged**
