### PR TITLE
Check R library loads when searching.

### PR DESCRIPTION
**Pull request by simonbyrne**
Gives a better error message for #143.

### CODE REVIEW

**Comment by simonbyrne** [comment]
Should now also give a better message if the version is too old (#74).

**Comment by simonbyrne** [comment]
Thoughts @randy3k ?

**Comment by randy3k** [comment]
It looks good. 

PS: it seems that Julia has changed the behaviour of `isnull(Nullable(1, true))`?

**Comment by simonbyrne** [comment]
Ah yes, I remember seeing that somewhere. It's now the opposite (the fields is now `hasvalue` instead of `isnull`). I can look at it tomorrow if you don't have time to do it today.

**Pull request merged**
