### PR TITLE
added a utility function to install packages

### PR DESCRIPTION
**Pull request by xiaodaigh**
Currently,
```julia
R"""
install.packages(pkgs)
"""
```
is failing. So I have added a function to install packages using `run`

### CODE REVIEW

**Comment by randy3k** [comment]
Try again with the master branch? `install.packages(pkgs)` should work now on Windows.

**Comment by xiaodaigh** [comment]
it doesn't. stuck at 
image

**Comment by randy3k** [comment]
put this in your `.Rprofile`

```
options(repos = c(CRAN = "https://cran.rstudio.com"))
```

**Comment by randy3k** [comment]
It still doesn't fix the whole issue, any prompts that pop out will essentially freeze the installation.

**Comment by palday** [comment]
@randy3k Would it make sense to change this to a documentation change rather than a code change?

**Comment by ViralBShah** [comment]
Just tested and works fine.

**Pull request closed without merging**
