### PR TITLE
test Conda

### PR DESCRIPTION
**Pull request by simonbyrne**
Keep #269 fixed.

### CODE REVIEW

**Comment by simonbyrne** [comment]
So using `ENV["R_HOME"] = "*"` causes problems when R is actually run. I think it might be better to use a variable like `ENV["R_CONDA"] = "TRUE"` or something along those lines?

**Comment by simonbyrne** [comment]
Okay, this should now be working.

The main question is what to do about Conda: do we want it to install automatically if it can't find an R installation (that's what the docs say, but it isn't actually the case)?

**Comment by simonbyrne** [comment]
@randy3k any thoughts?

**Comment by randy3k** [comment]
Sorry for the late reply. I am busy moving.

Most Julia users trying RCall would be regular R users already. I don't think it's necessary to install R automatically.

**Comment by ViralBShah** [comment]
I think the automatic installation stuff has too many challenges to get right. Might be better to remove all the Conda stuff altogether, and expect users to provide their own R.

**Comment by simonbyrne** [comment]
Yeah, I think we should look into getting rid of deps altogether.

**Pull request closed without merging**
