### PR TITLE
update formula copying to StatsModels v0.2.4

### PR DESCRIPTION
**Pull request by kleinschmidt**
The representation of Formulas has changed in StatsModels.  It now holds onto the whole formula expression (e.g., `Expr(:call, :~, ...)`) as well as the parsed expression and the left- and right-hand sub-expressions.

For copying from R to Julia, it's necessary to invoke the `@formula` model to trigger parsing of the formula expression. (That's not strictly true in this release, since it's just transforming the Expr, but it will be in the future to support things like arbitrary functions in formulae).

For Julia to R, in order to match the old behavior, I propose just copying the Expr of the original (un-parsed) formula (in the `ex_orig` field).  There are some situations (where the Formula is constructed manually from left and right-hand sub expressions) that the `ex_orig` field is an empty expression, but that's deprecated now.  In those cases, this PR pulls the parsed expression in the `ex` field.

### CODE REVIEW

**Comment by nalimilan** [comment]
Would there be any way to do this without calling `@eval`? It sounds too bad to have to call it just to create a formula: `@eval` is allowed to run any expression with all sort of possible effects, but here we just want to get one object as a result (so it's more like a function). It sounds more like `Meta.parse` AFAICT.

**Comment by randy3k** [comment]
It seems to me that the your implementation is quite fragile and is subject to be broken when StatModles removes the ex_orig field.

**Comment by kleinschmidt** [comment]
Currently all `@formula` does is something like `Meta.parse`, but my vision for the future involves doing more drastic transformations like creating anonymous functions to support arbitrary transformations like `log(a)` in the formula.  AFAIK that can't be done in a function because you run into world age issues.

@randy3k there are no plans to remove the `ex_orig` field; it'll always be useful for a formula to hold onto the original expression.  And I don't see how any other solution that relies on particular internal structure of the `Formula` struct is going to be less fragile.  The other alternative would be to add getter methods for the various parts, which I'd be open to.

**Comment by randy3k** [comment]
Thanks for the clarification about future plans. Going back to `@formula`, would you use `Formula(:(), :($lhs ~ $rhs), lhs, rhs) ` instead? I recently learnt that running `@eval` can have strong side effects.#238. Though it is likely that issue is not irrelevant to this PR, i still want to avoid `@eval` in function as much as possible.

**Comment by kleinschmidt** [comment]
I see. We'd have to trigger parsing, too (since the `*` transformations etc. are handled at macro time in v0.2.4), but I'm okay with that for now.  It may need to change in the future if/when the parsing step becomes more involved but good to keep it incremental I think.

**Comment by randy3k** [comment]
For CI fails because https://github.com/JuliaLang/METADATA.jl/pull/14404 has not been merged.

**Comment by kleinschmidt** [comment]
Right, the formula tests pass locally for me with this PR.

**Comment by randy3k** [comment]
I'd merge it once @dmbates adds suppport of the new version of StatModels at https://github.com/dmbates/MixedModels.jl

**Pull request merged**
