### PR TITLE
Axisarrays

### PR DESCRIPTION
**Pull request by randy3k**

### CODE REVIEW

**Comment by simonbyrne** [comment]
Personally I kind of like that AxisArrays are only loaded when used: we could do the same for DataFrames and CategoricalArrays.

**Comment by randy3k** [comment]
Even if we are using Requires.jl, we still need to keep the dependencies in the file [REQUIRE](https://github.com/JuliaInterop/RCall.jl/blob/master/REQUIRE) to avoid warnings complaining loading a package without requiring it.

So what are the advantages of using Requires.jl then? Users still have to download the dependencies. Given the precompiling speed of julia v1.0, I am not sure if there are any differences.

**Comment by simonbyrne** [comment]
No, you shouldn't need it in `REQUIRE`, though you may need it in `test/REQUIRE` if using it during testing.

**Comment by simonbyrne** [comment]
AxisArrays would still need to be added as a dependency of the project which uses it, but it doesn't need to be a dependency of RCall.

**Comment by randy3k** [comment]
It is weird. I am no longer reproduce the warning.

**Comment by randy3k** [comment]
So close it now and we may move all dependencies to Requires.jl.

**Pull request closed without merging**
