### PR TITLE
Improve conversion from CategoricalArray to factor

### PR DESCRIPTION
**Pull request by greimel**
Currently, only `CategoricalArray{String}` are converted to `factor` correctly. This doesn't work on `master`, but works with this PR.

`CategoricalArray{<:Number}`:
```julia
df_symbol = DataFrame(x = randn(100), y=randn(100), z1=rand([:a; :b], 100), z2=rand([:darkorange; :lightblue], 100))

categorical!(df_symbol, :x)
R"str($df_symbol)" # before: error, after: works as expected
```

`CategoricalArray{Symbol}`:
```julia
df_symbol = DataFrame(x = randn(100), y=randn(100), z1=rand([:a; :b], 100), z2=rand([:darkorange; :lightblue], 100))
ggplot(df_symbol) + geom_point(aes(x=:x, y=:y, color=:z1)) # doesn't work
ggplot(df_symbol) + geom_point(aes(x=:x, y=:y, color=:z2)) # uses colors "darkred" and "lightblue"
categorical!(df_symbol, :z2)
ggplot(df_symbol) + geom_point(aes(x=:x, y=:y, color=:z2)) # before: error - after: uses standard colors
```

The caveat is, that now a vector of `Symbol`s behaves quite differently if it's a `CategoricalVector`. (In this example above the colors change.)

This solves half of #331.

### CODE REVIEW

**Comment by nalimilan** [comment]
This makes sense AFAICT since R factors only allow string levels. However, due to this line:
https://github.com/JuliaInterop/RCall.jl/blob/1bd5c47ac86428eb501c017c4f534d97f21c3669/src/convert/default.jl#L266
all `CategoricalArray` objects will be converted to factors, even if their levels are not of type `String` or `Symbol`. This might be OK, but it deserves some discussion. For types other than strings, symbols and chars, it could be better to convert them to a plain vector of the corresponding type rather than to a factor.

@alyst Do you have an opinion? IIRC you work with non-string categorical vectors.

**Comment by alyst** [comment]
I would rather always convert *CategoricalArray* objects to factors.
If some *CategoricalVector{Float64}* (e.g. for a *timepoint* column in an experiment) becomes *numeric*, it'll affect the generation of the model matrix for `glm()` in an unexpected way.

**Comment by nalimilan** [comment]
Yeah. I guess one could argue otherwise and say that converting to string a value may destroy information (e.g. a date), but in practice we probably don't care.

**Comment by alyst** [comment]
We may introduce some additional R attribute that would store the factor levels in their original type.
Probably there are even some R packages (something from *tidyverse*?) that support non-character level types and `RCall` may use their classes (IIUC, it should still work even in the absence of the package, like *data.frame* / *tibble*).

**Comment by nalimilan** [comment]
Not that I know of: [forcats](https://github.com/tidyverse/forcats/) still uses standard factors (surprisingly).

**Pull request merged**
