### PR TITLE
Convert Date and DateTime to/from R

### PR DESCRIPTION
**Pull request by lelmiger**
Support `Data` and `DateTime` types by converting from/to R's `Date` and `POSIXct` classes.

```
julia> using RCall

julia> d = Dates.today()
2017-01-11

julia> tm = now()
2017-01-11T23:14:01.148

julia> R"""
       cat(paste0("Today's date is ", $d ,".\n"))
       cat(paste0("The current timestamp is ", $tm ,".\n"))
       """;
Today's date is 2017-01-11.
The current timestamp is 2017-01-11 23:14:01.

julia> R"""
       d <- as.Date(c("2010-10-10", "2009-09-09"))
       tm <- as.POSIXct(c("1942-04-02 04:42:42", "2020-02-20 20:02:20"), "UTC")
       """;

julia> rcopy("d")
2-element Array{Date,1}:
 2010-10-10
 2009-09-09

julia> rcopy("tm")
2-element Array{DateTime,1}:
 1942-04-02T04:42:42
 2020-02-20T20:02:20
```

### CODE REVIEW

**Comment by lelmiger** [comment]
Notice that conversion to/from R's `POSIXct` always occurs in UTC since julia's `DateTime` does not support time zones. This can lead to surprising results when converting `POSIXct` objects with differing or not explicitly set time zone:
```
julia> R"""tm <- as.POSIXct("2000-01-01 05:00", "Asia/Tokyo")""";

julia> rcopy("tm")
1999-12-31T20:00:00
```

**Comment by nalimilan** [comment]
Cool!

Though; how about creating [`ZonedDateTime`](https://github.com/JuliaTime/TimeZones.jl) objects instead, so that time zone information is preserved?

**Comment by lelmiger** [comment]
Converting `POSIXct` to `ZonedDateTime` is certainly possible.
I am not sure tough whether an additional dependency to [TimeZones.jl](https://github.com/JuliaTime/TimeZones.jl) is desirable for `RCall`.

**Comment by nalimilan** [comment]
I would say yes, since that's a small, pure-Julia dependency. Anyway, we'll also need e.g. to depend on NamedArrays/AxisArrays to preserve array names (https://github.com/JuliaInterop/RCall.jl/issues/144). At some point, optional dependencies should allow requiring only the features you actually use.

**Comment by randy3k** [comment]
I kind of like it, but it may complicate the work of passing custom R class object presented in https://github.com/JuliaInterop/RCall.jl/issues/138.

**Pull request closed without merging**
