### PR TITLE
add conversion from and to NamedTuple

### PR DESCRIPTION
**Pull request by tomhaber**
This PR adds conversions from/to `NamedTuple`. Seems easier to use than using `Dicts`, even if it uses the same R types underneath.

When supplying the names of the `NamedTuple`, it checks if the underlying R type matches exactly. Another approach would be to only select the entries specified (if available).

### CODE REVIEW

**Comment by ViralBShah** [comment]
Is this something that we can merge? I just happened to be here and see that this PR seems to work well with the CI and passes the new tests.

**Comment by ViralBShah** [comment]
I was hoping to re-run this with the new CI - but that will need rebasing to master.

**Comment by ViralBShah** [comment]
Can you rebase it to the latest master? 

Also @simonbyrne Can we merge this?

**Comment by ViralBShah** [comment]
@tomhaber If it helps, also happy to give you commit access here.

**Review by simonbyrne — APPROVED** [review]

**Comment by simonbyrne** [comment]
Thanks, sorry for the delay. I admit I don't pay much attention to this repo now.

**Comment by ViralBShah** [comment]
@tomhaber Thanks for the PR and have invited you to have write permissions on this repo.

**Pull request merged**
